FROM node:18-alpine as base
RUN apk add --no-cache g++ make py3-pip libc6-compat
WORKDIR /appWorkdir
COPY package*.json ./
EXPOSE 3001

FROM base as builder
WORKDIR /appWorkdir
COPY . .
RUN npm run build


FROM base as production
WORKDIR /appWorkdir

ENV NODE_ENV=production
RUN npm ci

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001
USER nextjs


COPY --from=builder --chown=nextjs:nodejs /appWorkdir/.next ./.next
COPY --from=builder /appWorkdir/node_modules ./node_modules
COPY --from=builder /appWorkdir/package.json ./package.json
COPY --from=builder /appWorkdir/public ./public

CMD npm start

FROM base as dev
ENV NODE_ENV=development
RUN npm install 
COPY . .
CMD npm run dev